const nodemailer = require('nodemailer');
const keys = require("../config/keys");

const transporter = nodemailer.createTransport({
    service: "Gmail",
    auth: {
        user: keys.transporterEmail,
        pass: keys.transporterPass
    }
});

const sendConfirmationMail = (to, url) => {
    transporter.sendMail({
        to: to,
        subject: "Confirmation Email - IIT Goa Placement Cell",
        html: `
            <div>
                Dear Student, <br> <br>
                Kindly click on this link: <a href="${url}"> Verify Account </a> to verify your email address. <br>
                <br>
                Placement Cell, <br>
                Indian Institute of Technology (IIT), Goa
            </div>
        
        `
    }, (err, info) => {
    });
};

const reportBugMail = (to, user, feature, description) => {
    transporter.sendMail({
        to: to,
        subject: "[PLACEMENT PORTAL] New bug has been reported",
        html: `
            <div>
                Hi Devs, <br><br>
                A bug report is generated by user with email ID: ${user}. <br>
                Feature: ${feature} <br>
                Description: ${description} <br><br>
                
                Placement Cell, <br>
                Indian Institute of Technology (IIT), Goa
            </div>
        `
    }, (err, info) => {
    });
};

const sendOTPMail = (to, otp) => {
    transporter.sendMail({
        to: to,
        subject: "OTP Email - IIT Goa Placement Cell",
        html: `
            <div>
                Dear Student, <br> <br>
                Use ${otp} to login and reset password once you login from profile settings for security reasons.<br>
                <i>If this was not sent by you. Kindly inform admin at the earliest.</i>
                <br> <br>
                Placement Cell, <br>
                Indian Institute of Technology (IIT), Goa
            </div>
        `
    }, (err, info) => {
    });
};

const sendApprovalMail = (to) => {
    transporter.sendMail({
        to: to,
        subject: "Profile Approval Email - IIT Goa Placement Cell",
        html: `
            <div>
                Dear Student, <br> <br>
                Your Profile has been approved by the Admin<br>
                <br>
                Placement Cell, <br>
                Indian Institute of Technology (IIT), Goa
            </div>
        
        `
    }, (err, info) => {
    });
};

const sendDisapprovalMail = (to, suggestion) => {
    transporter.sendMail({
        to: to,
        subject: "Profile Disapproval Email - IIT Goa Placement Cell",
        html: `
            <div>
                Dear Student, <br> <br>
                Your Profile has been disapproved by the Admin. Here are some suggested changes: <br><br>
                ${suggestion}
                <br><br>
                Placement Cell, <br>
                Indian Institute of Technology (IIT), Goa
            </div>
        
        `
    }, (err, info) => {
    });
};

const sendAnnouncementMail = (to, data) => {
    transporter.sendMail({
        to: to,
        subject: `${data.subject} - IIT Goa Placement Cell`,
        html: `
            <div>
                ${data.description}
                <br>
                Placement Cell, <br>
                Indian Institute of Technology (IIT), Goa
            </div>
        
        `
    }, (err, info) => {
    });
};

const createQueryMail = (to, user, subject, query) => {
    transporter.sendMail({
        to: to,
        subject: "[Placement Portal] - A new query from student",
        html: `
            <div>
                Dear Officer, <br><br>
                A query is asked by student with email: ${user}. <br>
                Subject: ${subject} <br>
                Query: ${query} <br><br>
                
                Placements Portal, <br>
                Indian Institute of Technology (IIT), Goa
            </div>
        `
    }, (err, info) => {
    });
};

const sendDisableMail = (to, reason) => {
    transporter.sendMail({
        to: to,
        subject: "Profile Disable Email - IIT Goa Placement Cell",
        html: `
            <div>
                Dear Student, <br> <br>
                Your Profile has been disabled by the Admin. The Reason for disabling your profile is: <br><br>
                ${reason}
                <br><br>
                Placement Cell, <br>
                Indian Institute of Technology (IIT), Goa
            </div>
        
        `
    }, (err, info) => {
    });
};

const sendEnableMail = (to) => {
    transporter.sendMail({
        to: to,
        subject: "Profile Enable Email - IIT Goa Placement Cell",
        html: `
            <div>
                Dear Student, <br> <br>
                Your Profile has been enabled by the Admin.
                <br><br>
                Placement Cell, <br>
                Indian Institute of Technology (IIT), Goa
            </div>
        
        `
    }, (err, info) => {
    });
};


module.exports = {
    sendConfirmationMail: sendConfirmationMail,
    reportBugMail: reportBugMail,
    sendOTPMail: sendOTPMail,
    sendDisapprovalMail: sendDisapprovalMail,
    sendAnnouncementMail: sendAnnouncementMail,
    sendApprovalMail: sendApprovalMail,
    createQueryMail: createQueryMail,
    sendDisableMail: sendDisableMail,
    sendEnableMail: sendEnableMail
};